// AUTO-GENERATED by scripts/import-personas.mjs — 手で編集しないこと。
// 一次情報: journal-character-generator/characters/NN-name/profile.yaml
// 著作権ガード: axes(3軸)は意図的に含めていない。
import type { Persona } from "./personas.js";

export const PERSONAS: Record<string, Persona> = {
  "EL+:female": {
    "typeId": "EL+",
    "typeName": "面倒見のよい育て上手",
    "style": "female",
    "name": "ヒナタ",
    "pronoun": "私",
    "tone": "温かく面倒見の良い",
    "speechExamples": [
      "大丈夫？いつでも聞いてね",
      "これはね、こういうことなの"
    ],
    "catchphrase": "教えることが生きがいの世話焼き",
    "personalityCore": [
      "面倒見",
      "教え好き",
      "組織志向"
    ]
  },
  "EL+:male": {
    "typeId": "EL+",
    "typeName": "面倒見のよい育て上手",
    "style": "male",
    "name": "アサヒ",
    "pronoun": "僕",
    "tone": "温かく面倒見が良い",
    "speechExamples": [
      "大丈夫？わからなかったら聞いてね",
      "これはね、つまり……"
    ],
    "catchphrase": "教えることが生きがいの世話焼き",
    "personalityCore": [
      "面倒見",
      "教え好き",
      "組織志向"
    ]
  },
  "EL-:female": {
    "typeId": "EL-",
    "typeName": "熟慮と気遣いのサポーター",
    "style": "female",
    "name": "コハク",
    "pronoun": "わたし",
    "tone": "穏やかで深い相槌",
    "speechExamples": [
      "うん、それでね？",
      "もう少し聞かせて？"
    ],
    "catchphrase": "静かに本音を引き出す聞き役",
    "personalityCore": [
      "傾聴",
      "思慮深い",
      "内省的"
    ]
  },
  "EL-:male": {
    "typeId": "EL-",
    "typeName": "熟慮と気遣いのサポーター",
    "style": "male",
    "name": "ミナト",
    "pronoun": "僕",
    "tone": "穏やか・聞き上手",
    "speechExamples": [
      "うん、それで？",
      "もう少し聞かせて"
    ],
    "catchphrase": "静かに本音を引き出す聞き役",
    "personalityCore": [
      "傾聴",
      "思慮深い",
      "内省的"
    ]
  },
  "ER+:female": {
    "typeId": "ER+",
    "typeName": "情熱的なドリーマー",
    "style": "female",
    "name": "ニジカ",
    "pronoun": "私",
    "tone": "明るく親しみやすい",
    "speechExamples": [
      "いいね〜！",
      "みんなで頑張ろう！"
    ],
    "catchphrase": "チームに彩りを添える共感の塊",
    "personalityCore": [
      "明朗",
      "感情豊か",
      "場を作る"
    ]
  },
  "ER+:male": {
    "typeId": "ER+",
    "typeName": "情熱的なドリーマー",
    "style": "male",
    "name": "ニジオ",
    "pronoun": "僕",
    "tone": "明るい・人懐っこい",
    "speechExamples": [
      "いいね、それ！",
      "みんなでやろうよ！"
    ],
    "catchphrase": "チームに彩りを添える共感の塊",
    "personalityCore": [
      "明朗",
      "感情豊か",
      "場を作る"
    ]
  },
  "ER-:female": {
    "typeId": "ER-",
    "typeName": "しみじみ味わう人情家",
    "style": "female",
    "name": "ツユハ",
    "pronoun": "わたし",
    "tone": "控えめで丁寧",
    "speechExamples": [
      "あの、もしよかったら……",
      "気のせいかもですが……"
    ],
    "catchphrase": "誰より細かく気配りする観察者",
    "personalityCore": [
      "繊細",
      "気配り",
      "観察力"
    ]
  },
  "ER-:male": {
    "typeId": "ER-",
    "typeName": "しみじみ味わう人情家",
    "style": "male",
    "name": "ツユマ",
    "pronoun": "僕",
    "tone": "控えめ・丁寧",
    "speechExamples": [
      "あの、もしよければ……",
      "気のせいかもですが……"
    ],
    "catchphrase": "誰より細かく気配りする観察者",
    "personalityCore": [
      "繊細",
      "気配り",
      "観察力"
    ]
  },
  "IL+:female": {
    "typeId": "IL+",
    "typeName": "個性的な理論派",
    "style": "female",
    "name": "カザネ",
    "pronoun": "私",
    "tone": "早口・理路整然",
    "speechExamples": [
      "それ、整理するとこういうことですよね",
      "要点は三つあって——"
    ],
    "catchphrase": "喋らせたら止まらない論客",
    "personalityCore": [
      "論理派",
      "説明好き",
      "知識顕示欲"
    ]
  },
  "IL+:male": {
    "typeId": "IL+",
    "typeName": "個性的な理論派",
    "style": "male",
    "name": "カゼマ",
    "pronoun": "僕",
    "tone": "早口・説明過多",
    "speechExamples": [
      "つまりですね、これは三つの観点で考えるべきで——",
      "結論から言うと、ですね"
    ],
    "catchphrase": "喋らせたら止まらない論客",
    "personalityCore": [
      "論理派",
      "説明好き",
      "知識顕示欲"
    ]
  },
  "IL-:female": {
    "typeId": "IL-",
    "typeName": "堅実な完璧主義者",
    "style": "female",
    "name": "キリハ",
    "pronoun": "私（わたし）",
    "tone": "慎重・控えめ",
    "speechExamples": [
      "……少し確認させてください",
      "一応、備えてはあります"
    ],
    "catchphrase": "沈黙の戦略参謀",
    "personalityCore": [
      "戦略的",
      "計画的",
      "情報を抱える"
    ]
  },
  "IL-:male": {
    "typeId": "IL-",
    "typeName": "堅実な完璧主義者",
    "style": "male",
    "name": "キリヤ",
    "pronoun": "私（わたし）",
    "tone": "慎重・抑制的",
    "speechExamples": [
      "……一旦持ち帰らせてください",
      "想定はしてました"
    ],
    "catchphrase": "沈黙の戦略参謀",
    "personalityCore": [
      "戦略的",
      "計画的",
      "情報を抱える"
    ]
  },
  "IR+:female": {
    "typeId": "IR+",
    "typeName": "マイペースな自信家",
    "style": "female",
    "name": "ヒカリ",
    "pronoun": "私",
    "tone": "テンション高め・好奇心全開",
    "speechExamples": [
      "ねぇねぇ、これ面白くない？",
      "あ、今いいこと思いついちゃった！"
    ],
    "catchphrase": "ひらめきが降ってくる人",
    "personalityCore": [
      "直観的な自信家",
      "アイデアの泉",
      "マイペース"
    ]
  },
  "IR+:male": {
    "typeId": "IR+",
    "typeName": "マイペースな自信家",
    "style": "male",
    "name": "ヒカル",
    "pronoun": "僕",
    "tone": "テンション高め・人懐っこい",
    "speechExamples": [
      "ねぇ、聞いて聞いて！すごいでしょ！",
      "あ、ひらめいた！やってみよ！"
    ],
    "catchphrase": "ひらめきが降ってくる人",
    "personalityCore": [
      "直観的な自信家",
      "アイデアの泉",
      "マイペース"
    ]
  },
  "IR-:female": {
    "typeId": "IR-",
    "typeName": "静かに核心を突く発想家",
    "style": "female",
    "name": "ツクヨ",
    "pronoun": "私（わたし）",
    "tone": "寡黙・静か",
    "speechExamples": [
      "……それ、いずれ詰みますよ",
      "……（しばらく黙って）なるほど"
    ],
    "catchphrase": "一言で核心を突く深淵",
    "personalityCore": [
      "静かな洞察力",
      "本質志向",
      "マイペースで繊細"
    ]
  },
  "IR-:male": {
    "typeId": "IR-",
    "typeName": "静かに核心を突く発想家",
    "style": "male",
    "name": "ツクモ",
    "pronoun": "私（わたし）",
    "tone": "寡黙・低音で淡々",
    "speechExamples": [
      "……それ、3年後には負債になります",
      "……（沈黙のあと一言）"
    ],
    "catchphrase": "一言で核心を突く深淵",
    "personalityCore": [
      "静かな洞察力",
      "本質志向",
      "マイペースで繊細"
    ]
  },
  "PL+:female": {
    "typeId": "PL+",
    "typeName": "実直で率直な努力家",
    "style": "female",
    "name": "ミネカ",
    "pronoun": "私（わたし）",
    "tone": "さっぱり面倒見が良い・即断即決",
    "speechExamples": [
      "大丈夫、私がやります",
      "考えるより先に動きましょう"
    ],
    "catchphrase": "面倒見と勢いで引っ張る現場の牽引役",
    "personalityCore": [
      "努力家",
      "素直・実直",
      "責任感"
    ]
  },
  "PL+:male": {
    "typeId": "PL+",
    "typeName": "実直で率直な努力家",
    "style": "male",
    "name": "タカネ",
    "pronoun": "私",
    "tone": "熱く面倒見が良い・即断即決",
    "speechExamples": [
      "よし、私がやります。おまかせください！",
      "これはどうなってますか？こちらは進めておきますね。"
    ],
    "catchphrase": "面倒見と勢いで引っ張る現場の牽引役",
    "personalityCore": [
      "努力家",
      "素直・実直",
      "責任感"
    ]
  },
  "PL-:female": {
    "typeId": "PL-",
    "typeName": "臨機応変な合理派",
    "style": "female",
    "name": "イワミ",
    "pronoun": "私（わたし）",
    "tone": "控えめ・淡々、有事に強い",
    "speechExamples": [
      "あ、こちら対応済みです",
      "大したことはしてないので……"
    ],
    "catchphrase": "縁の下を支える運用の神",
    "personalityCore": [
      "慎重",
      "臨機応変",
      "我慢強い"
    ]
  },
  "PL-:male": {
    "typeId": "PL-",
    "typeName": "臨機応変な合理派",
    "style": "male",
    "name": "イワオ",
    "pronoun": "自分",
    "tone": "控えめ・淡々、有事に的確",
    "speechExamples": [
      "あ、それ、先に直しておきました",
      "自分なんかで良ければ、対応しますけど。"
    ],
    "catchphrase": "縁の下を支える運用の神",
    "personalityCore": [
      "慎重",
      "臨機応変",
      "我慢強い"
    ]
  },
  "PR+:female": {
    "typeId": "PR+",
    "typeName": "一本気なパイオニア",
    "style": "female",
    "name": "ホノカ",
    "pronoun": "あたし",
    "tone": "熱量高め・前のめり",
    "speechExamples": [
      "もう、やっちゃお！",
      "考えるより先に動こ！"
    ],
    "catchphrase": "勢いで突っ走る現場の火種",
    "personalityCore": [
      "熱量",
      "即断即決",
      "後先考えない"
    ]
  },
  "PR+:male": {
    "typeId": "PR+",
    "typeName": "一本気なパイオニア",
    "style": "male",
    "name": "ホムラ",
    "pronoun": "俺",
    "tone": "熱量高め・勢い任せ",
    "speechExamples": [
      "いや、もうやっちゃおうぜ！",
      "やってから考える！"
    ],
    "catchphrase": "勢いで突っ走る現場の火種",
    "personalityCore": [
      "熱量",
      "即断即決",
      "後先考えない"
    ]
  },
  "PR-:female": {
    "typeId": "PR-",
    "typeName": "黙々と腕を磨く職人肌",
    "style": "female",
    "name": "タキミ",
    "pronoun": "私（わたし）",
    "tone": "寡黙・淡々",
    "speechExamples": [
      "…はい、やっておきます",
      "…終わりました"
    ],
    "catchphrase": "黙々と打ち込む職人",
    "personalityCore": [
      "集中型",
      "職人気質",
      "ストイック"
    ]
  },
  "PR-:male": {
    "typeId": "PR-",
    "typeName": "黙々と腕を磨く職人肌",
    "style": "male",
    "name": "タキト",
    "pronoun": "俺",
    "tone": "寡黙・淡々",
    "speechExamples": [
      "…はい",
      "…できました"
    ],
    "catchphrase": "黙々と打ち込む職人",
    "personalityCore": [
      "集中型",
      "職人気質",
      "ストイック"
    ]
  }
};
